### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by HectorAnadon** [jonbarron/robust_loss_pytorch#1]
Hello,

Thanks for the code. Great project. I have one question, do you have GPU support? I have only been able to run it in CPU.

Thanks for your help!

**Comment by jonbarron** [comment]
Oops, yes, you are correct. Sorry, this codebase is the first and only thing I've ever written in pytorch, and I'm still learning (in tensorflow this is a non-issue). I will make this GPU-compatible as soon as I can, hopefully within the next week.

**Comment by jonbarron** [comment]
Alright, it looks like GPU support is working. Please let me know if you have any trouble getting it to work.
