### ISSUE TITLE
How to apply the robust loss in Monodepth Estimation？

### ISSUE THREAD

**Issue by gaopeng91** [jonbarron/robust_loss_pytorch#13]
Hi，
 Thanks for your wonderful job，I am confused on that how to apply the robust loss on monodepth Estimation？is it used to instead photo-metirc loss？could you give me more explanation about that？ 
Thanks

**Comment by jonbarron** [comment]
Hi, unfortunately we don't have a code release for the monocular depth estimation experiments of the paper (though that code is in TF anyways so it likely isn't what you're looking for). I believe that there are Pytorch implementations of SFMLearner on Github, and using this loss should be straightforward: just delete the existing multiscale photometric loss and the smoothness term and add in AdaptiveImageLossFunction on the full-res image with:
scale_lo=0.01
scale_init=0.01
and default settings for the rest and it should work (you may need to fiddle with the value of wavelet_scale_base).
Appendix H of the paper goes into more detail on this.

If you do end up porting this code to a PyTorch codebase and don't get the results you're expecting, please let me know and I'll do my best to help.

**Comment by gaopeng91** [comment]
Thanks for your help！I will try it
