### ISSUE TITLE
Loss value

### ISSUE THREAD

**Issue by KeniMardira** [jonbarron/robust_loss_pytorch#2]
I have tried implementing this for a project of mine and the loss went negative. Is this expected? Should I take the absolute of my residual before passing it to the loss function?

**Comment by jonbarron** [comment]
If you call the loss in general.py, it should never go negative. The loss produced by adaptive.py is actually a negative log-likelihood, so it can go negative depending on the value of the `scale` parameter.

**Comment by KeniMardira** [comment]
makes perfect sense, thanks for the quick response
