### ISSUE TITLE
is adaptive loss suitable for 3d shape reconstruction?

### ISSUE THREAD

**Issue by qiminchen** [jonbarron/robust_loss_pytorch#30]
Hi, I'm wondering if the adaptive loss is suitable for 3d shape reconstruction, especially for implicit representation, e.g, predicting inside/outside values? Thanks

**Comment by jonbarron** [comment]
Hard to say, if it's a regression task where you don't know the noise model a-priori, it could be helpful. If you have a noise model then this probably isn't a good idea.
