### ISSUE TITLE
AdaptiveLossFunction question

### ISSUE THREAD

**Issue by 110dazhi** [jonbarron/robust_loss_pytorch#31]
when I use the same target and the same predict, like "target = a" and "predict=a", I find the AdaptiveLossFunction  is not equal 0. Is it normal? 
![adative](https://user-images.githubusercontent.com/57225932/157915385-16a3872d-e616-472f-85b6-78efa217fe44.png)

**Comment by jonbarron** [comment]
Yep that makes sense, the adaptive loss is a negative log likelihood, so it won't necessarily bottom out at 0.
