### ISSUE TITLE
Using this loss function for depth priors in NeRF?

### ISSUE THREAD

**Issue by morsingher** [jonbarron/robust_loss_pytorch#32]
Hi Jon, first of all, thanks for all the amazing work you keep doing. 

I am working on integrating pixelwise depth priors into NeRF, in a similar way with respect to your recent paper: https://arxiv.org/pdf/2112.03288.pdf. I was wondering why you didn't try to use this robust loss function instead of GNLL. My intuition is that this should be more robust to wrong depth estimates in textureless areas or non-Lambertian surfaces. Is there something I'm missing or do you think it might be worth to try it out?

**Comment by jonbarron** [comment]
Hey thanks for the kind words. That seems like a totally reasonable idea!

**Comment by morsingher** [comment]
Cool, I'll try and let you know!
